### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by dandv** [VladShcherbin/flex-grid#1]
How does this project compare with @kristoferjoseph's popular [flexboxgrid](https://github.com/kristoferjoseph/flexboxgrid)?

**Comment by VladShcherbin** [comment]
@dandv Hi, I saw that project, but it was written in css and I needed a scss version - so I created it by myself. I also added visibility classes and a stretch class. All in all, they work 90% the same.

I've created gh-pages [link](http://vladshcherbin.github.io/flexbox-grid) with all the docs.

Maybe you can have a look and tell me, do I need to change smth or typos/etc?

**Comment by VladShcherbin** [comment]
Readme created, website is also working.
